### ISSUE TITLE
Question about MVP: Search Listings

### ISSUE THREAD

**Issue by samsongs1991** [alexlolas/SkyBnB#2]
Do you plan to add the listings on an interactive map? Or will it be more like having a list of cities and then clicking on a city name which will show you the listings in that city?

If you plan to add a searchable map, it may take you more like 2-4 days to get that figured out so you want to be sure to take that into account in your timeline.

**Comment by alexlolas** [comment]
I am planning on doing an interactive map, ill add some more days to account for it thanks!

**Comment by samsongs1991** [comment]
Okay, sounds good. It's possible to get the map going in 1 day but on average I'd say 2 or 3 days for most people.
