### ISSUE TITLE
Revisions for FRONTEND ROUTES

### ISSUE THREAD

**Issue by samsongs1991** [alexlolas/SkyBnB#6]
Based on your current frontend routes, I think you may misunderstand what frontend routing is doing. 
For example, you currently have a route "/likes" that only renders the "LikeIndex" component. So essentially what this means is that if a user navigates to the url "https://your-fsp-clone.com/#/likes" then the webpage will render a list of all the "likes". 

Correct me if I'm mistaken, but I think what you want instead is for the user to navigate to the url "https://your-fsp-clone.com/#/listings/3" which would render details for listing ID: 3 with comments. Each comment could have a button for "likes" that you could click to show a modal with a list of "likes".

As you can see, one frontend route will normally render several components. You do not need a specific frontend route to render every single component. You will have revise your frontend routing with that in mind.

**Comment by alexlolas** [comment]
thank you for that, I was confused going through this but it makes more sense with that explanation, Ill go through tonight and refactor it.
